name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build guide
      run: |
        cd guide
        ./gradlew asciidoctor
    - name: Build step1
      run: |
        cd step1
        ./gradlew build
    - name: Build step2
      run: |
        cd step2
        ./gradlew build
